# Add your Google Cloud API key here
GOOGLE_API_KEY = "AIzaSyDcWsp0Grtp8OQ60AvcipnPaEuCANJ9XWk"

# Add your News API key here
NEWS_API_KEY = "6e8f2fe267884bc0a5fc3deeb3fe1cf3"

# Add your OpenAI API key here for enhanced fact checking
OPENAI_API_KEY = "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"